import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ContactProvider } from "./context/contact-context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Porfolio du développeur front end Nahoua",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-blue-900 text-slate-50`}
      >
        <ContactProvider>
          {children}
        </ContactProvider>
        
      </body>
    </html>
  );
}
